import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {Button} from "../components/Button/Button";
import {Scores} from "../components/Scores/Scores";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Movizz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={'main'}>
        <h1 className={'title-1'}>Welcome to <span>Movizz</span></h1>
        <div className={styles.rules}>
            <p className={'text-1'}>
                Welcome to the quizz ! You'll be asked a series of "Yes or No" questions. Answer as many as you can in the allowed time ! Good luck !
            </p>
        </div>
        <Scores />
        <Button href="/quiz" text="Start quiz" />
      </main>
    </div>
  )
}
